### PR TITLE
Support for overriding the k6 image

### PR DESCRIPTION
**Pull request by jmdacruz**
Support for overriding the k6 image. Suggested by @dgzlopes  in https://github.com/k6io/operator/issues/15#issuecomment-848648427

### CODE REVIEW

**Review by dgzlopes — APPROVED** [review]
LGTM! Thanks :)

**Comment by jmdacruz** [comment]
While trying to test this approach, I realize that we would also need the ability to expose extra ports on the container (so that Prometheus can scrape the metrics on port `5656` in this case). I could add this capability on this PR too

**Comment by jmdacruz** [comment]
@dgzlopes I took a stab at supporting extra ports on the CR, so that we can expose other ports for custom operator images

**Comment by majnos** [comment]
Would be nice if you could also update readme how to make prometheus work with k6-operator. Just some bullet points.

**Comment by jmdacruz** [comment]
@majnos I just added updated the readme with info on how use extensions, with the Prometheus extension as an example

**Comment by majnos** [comment]
something is wrong ... not sure what

time="2021-05-28T11:58:56Z" level=error msg="invalid output type 'prometheus', available types are: cloud, csv, datadog, influxdb, json, kafka, statsd"

**Comment by jmdacruz** [comment]
@majnos note that the error happens on your last stage, when you are trying to copy something that the "builder" image probably does not have (the `/workspace/manager` folder).

**Comment by jmdacruz** [comment]
@dgzlopes what else do we need to merge this PR?

**Comment by dgzlopes** [comment]
Nothing more :) 

Thanks for adding the extra docs! Merging.

**Comment by jmdacruz** [comment]
thanks @dgzlopes! One last thing: how do we trigger a new build for the operator image so that Docker Hub is updated?

**Comment by Juandavi1** [comment]
Hi guys, this still dont works :(

**Comment by dgzlopes** [comment]
Sorry for the late response! @simskij updated the Docker Image. Everything should work now.

**Comment by dgzlopes** [comment]
We should add #20 😄

**Comment by Juandavi1** [comment]
It works !! Thaks guys

**Pull request merged**
