### PR TITLE
Feat/pod struct

### PR DESCRIPTION
**Pull request by KnechtionsCoding**
Creates a PodSpec, migrates podMetadata under the PodSpec. It also adds the NodeSelector, AntiAffinity, and Env to the Runner. NodeSelector and AntiAffinity are also passed to the starter object (env isn't, but can be added easily).

### CODE REVIEW

**Comment by KnechtionsCoding** [comment]
Closes #32 and #8

**Comment by mikaelkundert** [comment]
This idea and solutions looks good.

I was slightly worried about using name `Pod` since it could cause some confusion with `corev1.Pod` or `corev1.PodSpec`. But after longer thought I think using `Pod` term is OK.

**Comment by KnechtionsCoding** [comment]
@mikaelkundert the other option was something like `k6pod` but that seemed extra verbose and not super necessary

**Comment by mikaelkundert** [comment]
> @mikaelkundert the other option was something like `k6pod` but that seemed extra verbose and not super necessary

Yeah I agree. I think `Pod` might be OK here. This term is used only within Go and not in Yamls, so contributors should be aware of the context pretty easily.

**Pull request merged**
